
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Toplevel_C5G_GPIO(

	//////////// CLOCK //////////
	input 		          		CLOCK_125_p,
	input 		          		CLOCK_50_B5B,
	input 		          		CLOCK_50_B6A,
	input 		          		CLOCK_50_B7A,
	input 		          		CLOCK_50_B8A,

	//////////// LED //////////
	output		     [7:0]		LEDG,
	output		     [9:0]		LEDR,

	//////////// KEY //////////
	input 		          		CPU_RESET_n,
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================
washing_machine u1_washing_machine(
	.rst_n							(CPU_RESET_n),
	.clk50m							(CLOCK_50_B5B),
	//sensors
	.start							(SW[0]),
	.full								(SW[1]),
	.hot								(SW[2]),
	.clean							(SW[3]),
	.dry								(SW[4]),
	//actuators
	.door_lock						(LEDR[0]),
	.valve							(LEDR[1]),	
	.heater							(LEDR[2]),
	.motor_wash						(LEDR[3]),	
	.motor_spin						(LEDR[4]),	
	.pump								(LEDR[5])

);


endmodule
