// -------------------------------------------------------------
// 
// File Name: hdlsrc/adder_code_gen/add_sl_s.v
// Created: 2018-01-11 16:03:35
// 
// Generated by MATLAB 9.3 and HDL Coder 3.11
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: add_sl_s
// Source Path: adder_code_gen/add_sl_s
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module add_sl_s
          (x,
           y,
           sum);


  input   signed [7:0] x;  // int8
  input   signed [7:0] y;  // int8
  output  signed [7:0] sum;  // int8

  wire signed [7:0] Sum_out1;  // int8


  assign Sum_out1 = x + y;



  assign sum = Sum_out1;

endmodule  // add_sl_s

