// -------------------------------------------------------------
// 
// File Name: hdlsrc/adder_code_gen/add_sl_s_prot.v
// Created: 2018-01-11 16:03:28
// 
// Generated by MATLAB 9.3 and HDL Coder 3.11
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: add_sl_s_prot
// Source Path: adder_code_gen/add_sl_s_prot
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module add_sl_s_prot
          (x,
           y,
           sum);


  input   signed [7:0] x;  // int8
  input   signed [7:0] y;  // int8
  output  signed [7:0] sum;  // int8

  wire signed [8:0] add_add_temp;  // sfix9
  wire signed [8:0] add_1;  // sfix9
  wire signed [8:0] add_2;  // sfix9
  wire signed [7:0] add_out1;  // int8


  assign add_1 = {x[7], x};
  assign add_2 = {y[7], y};
  assign add_add_temp = add_1 + add_2;
  assign add_out1 = ((add_add_temp[8] == 1'b0) && (add_add_temp[7] != 1'b0) ? 8'sb01111111 :
              ((add_add_temp[8] == 1'b1) && (add_add_temp[7] != 1'b1) ? 8'sb10000000 :
              $signed(add_add_temp[7:0])));



  assign sum = add_out1;

endmodule  // add_sl_s_prot

